baseURL = "https://marcelo-franceschini.github.io/my-hugo-personal/"
languageCode = "pt-br"
title = "Marcelo Franceschini"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Marcelo Franceschini"
    subtitle = "Bem-vindo ao meu site pessoal"
    imageUrl = ""
    imageTitle = ""
    [[params.profileMode.buttons]]
      name = "Posts"
      url = "/posts"
    [[params.profileMode.buttons]]
      name = "GitHub"
      url = "https://github.com/marcelo-franceschini"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/marcelo-franceschini"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
